services:
  bookingapp.api:
    container_name: bookingapp.api
    image: bookingapp.api
    build:
      context: .
      dockerfile: BookingApp.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Database: Host=bookingapp.database;Port=5432;Database=booking_app;Username=postgres;Password=postgres
      Serilog__WriteTo__1__Args__serverUrl: http://bookingapp.seq:5341
    ports:
      - "8080:8080"
    depends_on:
      bookingapp.database:
        condition: service_healthy
      bookingapp.seq:
        condition: service_started

  bookingapp.database:
    container_name: bookingapp.database
    image: postgres:18
    environment:
      POSTGRES_DB: booking_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bookingapp-postgres18-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_app"]
      interval: 5s
      timeout: 5s
      retries: 10

  bookingapp.seq:
    container_name: bookingapp.seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - bookingapp-seq-dev-data:/data

volumes:
  bookingapp-postgres18-data:
  bookingapp-seq-dev-data:
