<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookingApp.Application\BookingApp.Application.csproj" />
      <ProjectReference Include="..\BookingApp.Domain\BookingApp.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.2" />
    </ItemGroup>

</Project>
