<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookingApp.Application\BookingApp.Application.csproj" />
      <ProjectReference Include="..\BookingApp.Infrastructure\BookingApp.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Endpoints\Bookings\" />
      <Folder Include="Endpoints\ConferenceHalls\" />
      <Folder Include="Endpoints\Reports\" />
    </ItemGroup>

</Project>
