<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="10.2.3" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
        <PackageReference Include="AutoMapper" Version="16.2.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="4.3.0" />
        <PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookingApp.Bll.Common\BookingApp.Bll.Common.csproj" />
      <ProjectReference Include="..\BookingApp.Bll\BookingApp.Bll.csproj" />
      <ProjectReference Include="..\BookingApp.Dal.SqlServerRepositories\BookingApp.Dal.SqlServerRepositories.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
